name: angular_accordion

version: 0.1.0
author: Mike Mitterer  <office@mikemitterer.at>
description: Sample for Angular-Component

environment:
  sdk: '>=1.3.0 <2.0.0'

dependencies:
  browser: any

  validate: any
  console_log_handler: any

  di:               '>=3.3.1 <4.0.0'
  angular:           ">=1.0.0 <2.0.0"

  #">=0.14.0 <1.0.0"

transformers:
- angular:
    dart_sdk: "/usr/local/opt/dart/libexec"
